---
title: "Shapley"
author: "Anna Wiewer"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Read data file

```{r}

dataset <- read.csv("/Users/annawiewer/Desktop/Analytics Edge/Group project/Data/dataset (3).csv")

# Convert 'target' variable into a factor
dataset$Target <- factor(dataset$Target)
str(dataset)

#Redefine values for target variable
dataset <- dataset %>%
  mutate(Target = case_when(
    Target == 'Dropout' ~ 0,
    Target == 'Enrolled' ~ 2,
    Target == 'Graduate' ~ 1
  ))

#Note: imbalance in data set: Graduate (2209), Dropout (1421), Enrolled (794)

#Dataset with only enrolled students:
enrolled_data <- dataset[dataset$Target == 2, ]

# Dataset with drop and grad:
dropout_graduate_data <- dataset[dataset$Target %in% c(0, 1), ]

```

# All variables
```{r}
## All variables

# Assign target and features
target <- numeric_dropout_graduate_data$Target
features <- numeric_dropout_graduate_data[, names(numeric_dropout_graduate_data) != "Target"]


# Split data into training and testing sets
set.seed(123)  # Setting seed for reproducibility
indices <- sample(1:nrow(features), size = 0.8 * nrow(features))
train_features <- features[indices, ]
train_target <- target[indices]
test_features <- features[-indices, ]
test_target <- target[-indices]
```

#Calculate the shapley values for xgboost
```{r}
#Calculate the shapley values for xgboost

install.packages("SHAPforxgboost")

# run the model with built-in data
suppressPackageStartupMessages({
  library("SHAPforxgboost"); library("ggplot2"); library("xgboost")
  library("data.table"); library("here")
})

library("SHAPforxgboost")
library(xgboost)


y_var <-  train_target
dataX <- as.matrix(train_data[, !colnames(test_data) %in% "Target"])

param_list <- list(objective = "reg:squarederror",  # For regression
                   eta = 0.02,
                   max_depth = 10,
                   gamma = 0.01,
                   subsample = 0.95
)

mod_xg <- xgboost::xgboost(data = dataX, 
                        label = as.matrix(train_data$Target), 
                        params = param_list, nrounds = 10,
                        verbose = FALSE, nthread = parallel::detectCores() - 2,
                        early_stopping_rounds = 8)


shap_values <- shap.values(xgb_model = mod_xg, X_train = dataX)
shap_values$mean_shap_score

shap_values_drop <- shap_values$shap_score

# shap.prep() returns the long-format SHAP data from either model or
shap_long_drop <- shap.prep(xgb_model = mod_xg, X_train = dataX)
# is the same as: using given shap_contrib
shap_long_drop <- shap.prep(shap_contrib = shap_values_drop, X_train = dataX)

# **SHAP summary plot**
shap.plot.summary(shap_long_drop)

```

